Storybook updates
fourkitchens/fourkitchens-karaoke pull request #7
Opened 2022-09-08 20:27 UTC by Gregg-Hendrix

## Purpose:
- Coming soon

### Ticket(s)
[Description](https://app.clickup.com/t/2qmd1nu)

### Pull Request Deployment:
See linked environment in comments.

### Functional Testing:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

### Notes:
_Additional notes_

2022-09-09 14:56 UTC, generalredneck requested changes
I think this needs some work or I need an explanation :P

2022-09-09 14:56 UTC, generalredneck commented on web/themes/custom/kitchen_karaoke/components/02-molecules/recent-requests/_block-recent-requests.twig
> +        {{  }}
So nothing is outputted here if that's the case, should we keep it?

My thoughts here is that content should be populated... and you can make it populate in the CMS by logging in and creating a song request locally.

2022-09-12 15:43 UTC, Gregg-Hendrix commented on web/themes/custom/kitchen_karaoke/components/02-molecules/recent-requests/_block-recent-requests.twig
> +        {{  }}
I will do that today (create a song request locally).

My purpose was to get this molecule to show up in storybook, though I think I need to create the atom of "song request" then `include` that in this molecule. I think I kind of worked backwards on this one and will now create the atom :)

2022-09-13 13:53 UTC, generalredneck commented on web/themes/custom/kitchen_karaoke/components/02-molecules/recent-requests/_block-recent-requests.twig
> +        {{  }}
As long as it was intentional and there's an task to go back and do that... that's fine. As a resolution.. add a comment to your code with a `todo:` so that in the next PR you do it's replaced.

2022-09-13 13:54 UTC, generalredneck commented on web/themes/custom/kitchen_karaoke/components/02-molecules/recent-requests/_block-recent-requests.twig
> +        {{  }}
or you can create a blank atom with a todo in it.

2022-09-13 17:12 UTC, Gregg-Hendrix commented on web/themes/custom/kitchen_karaoke/components/02-molecules/recent-requests/_block-recent-requests.twig
> +        {{  }}
Thank you for letting me know how to resolve this, I have now implemented your suggestion. Thank you Allan!

2022-09-20 13:15 UTC, mikeethedude commented
@generalredneck or @Gregg-Hendrix It seems like this PR isn't needed now that we are using a different theme, yes? We should probably close this and port any needed changes to the new theme in a different PR.

2022-10-01 13:25 UTC, generalredneck commented
@Gregg-Hendrix You would have more insight into this. I for some reason thought we had merged all this.

2022-10-19 14:48 UTC, closed without merging